spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.143.247:3306/service?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Lyp82nlf

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





application:
  qiniu:
    ak: xxxx
    sk: xxxx
    bucket: xxxx
    path: xxxx